### ISSUE TITLE
FFmpegAVS2 configure failed

### ISSUE THREAD

**Issue by tonypccheny** [pkuvcl/davs2#1]
when I use ./configure in folder FFmpegAVS2 on linux platform,davs2_decoder_decode check failed;but if i modify this function to davs2_decoder_open,./configure success;later when I use make -j2 in FFmpegAVS2,i meet some compile errors,such as:
libavcodec/libdavs2.c: In function ‘DumpFrames’:
libavcodec/libdavs2.c:80:27: error: ‘davs2_picture_t’ has no member named ‘ret_type’
     if (pic == NULL || pic->ret_type == DAVS2_GOT_HEADER) {
                           ^
libavcodec/libdavs2.c:92:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
     const int bytes_per_sample = pic->bytes_per_sample;
     ^
▽ibavcodec/libdavs2.c:96:29: error: ‘davs2_picture_t’ has no member named ‘width’
         int size_plane = pic->width[i] * pic->lines[i] * bytes_per_sample;
                             ^
libavcodec/libdavs2.c:99:31: error: ‘davs2_picture_t’ has no member named ‘width’
         frm->linesize[i] = pic->width[i] * bytes_per_sample;
                               ^
libavcodec/libdavs2.c: In function ‘ff_davs2_end’:
libavcodec/libdavs2.c:123:9: warning: format ‘%llx’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘void *’ [-Wformat=]
         av_log(avctx, AV_LOG_WARNING, "[davs2] decoder destroyed. 0x%llx; frames %d\n", cad->decoder, cad->decoded_frames);        
         ^
libavcodec/libdavs2.c: In function ‘davs2_decode_frame’:
libavcodec/libdavs2.c:143:26: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
         cad->packet.data = buf_ptr;
                          ^
libavcodec/libdavs2.c:155:31: error: ‘davs2_picture_t’ has no member named ‘ret_type’
             if (cad->out_frame.ret_type != DAVS2_DEFAULT) {
                               ^
libavcodec/libdavs2.c:168:24: error: ‘davs2_packet_t’ has no member named ‘marker’
             cad->packet.marker = 0;
                        ^
libavcodec/libdavs2.c:169:30: warning: assignment discards ‘const’ qualifier from pointer target type [enabled by default]
             cad->packet.data = buf_ptr;
                              ^
libavcodec/libdavs2.c:175:13: error: implicit declaration of function ‘davs2_decoder_decode’ [-Werror=implicit-function-declaration]
             len = davs2_decoder_decode(cad->decoder, &cad->packet, &cad->headerset, &cad->out_frame);
             ^
libavcodec/libdavs2.c:177:31: error: ‘davs2_picture_t’ has no member named ‘ret_type’
+++++++++++++++I think davs2's verion is not right,but I alreadly use the most new version of davs2;
can someone help me? thanks very much;

**Comment by hwrenx** [comment]
Actually, indeed, this error is caused by wrong version of avs2. After v1.4.95, we changed our api for better performance, while FFmpegAVS2 is still under updating.

**Comment by tonypccheny** [comment]
@hwrenx thanks very much，I will wait the new version of ffmpegavs2 to fix this problem at github,wating for the good news.

**Comment by tonypccheny** [comment]
Hi,hwrenx when can i get the new version of ffmpegavs2 which fix the problem above,thanks very much.
