### ISSUE TITLE
关于随机解码opengop会某些gop的帧解不出来

### ISSUE THREAD

**Issue by liuzhezhe123** [pkuvcl/davs2#17]
对于avs2的ES流，已经解析出来所有的gop信息以及位置偏移。现在进行seek操作时直接定位到一个完整的gop信息，对数据流用davs2进行解码，对于closegop的情况都可以解出来每一帧，但是对于opengop有一些gop的最后几帧解不出来。
对于opengop的随机解码现在支持吗？
谢谢。

**Comment by hwrenx** [comment]
您好，OpenGOP模式下每个GOP开始和最后几帧可能会参考其他GOP，缺失参考帧时无法解码是正常的。确保每个关键帧前序列头信息完整送入解码器后OpenGOP模式可以随机解码。

**Comment by liuzhezhe123** [comment]
您好，非常谢谢。现在类型是GB帧的opengop可以解出来，其他的解出来的都是 I 帧，现在我有个疑问，opengop的第一帧都有什么类型啊，可以给我推荐一些资料吗？谢谢。

**Comment by hwrenx** [comment]
请查阅AVS2标准文档
