### ISSUE TITLE
configure fail with "endian test failed"

### ISSUE THREAD

**Issue by mypopydev** [pkuvcl/davs2#2]
barry@barry-HP-ENVY-Notebook:~/Sources/xavs2/davs2/build/linux$ uname -a

Linux barry-HP-ENVY-Notebook 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

barry@barry-HP-ENVY-Notebook:~/Sources/xavs2/davs2/build/linux$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

barry@barry-HP-ENVY-Notebook:~/Sources/xavs2/davs2/build/linux$ ./configure 
endian test failed

**Comment by luofalei** [comment]
By replacing the `--std=c++11` as `--std=gnu++11`, this compiling error was solved in my virtual machine with `Ubuntu 17.10` and `g++ 7.3.0`,

Another compiling error could be solved by modify the `configure` parameter by typing
```
$ ./configure --enable-pic
$ make -j
```
