### ISSUE TITLE
Final linking failed (GNU ld)

### ISSUE THREAD

**Issue by tripulse** [pkuvcl/davs2#21]
Source files compile down to object files pretty well, but at the linking stage if fails to link which results in a incomplete build. The branch I chose for building is `master`.

#### Reproduction
the same instructions described in the [`README.md`][instructions].

#### Expected behavior
In terminal when `make` is executed this should display:
```
make: Circular /home/tryamid/Projects/davs2/source/test/test.c <- /home/tryamid/Projects/davs2/source/test/test.c dependency dropped.
 [linking execution] davs2 
g++ -o davs2  test/test.o libdavs2.a  -m64  -lm -lpthread
/usr/bin/ld: libdavs2.a(blockcopy8.o): relocation R_X86_64_32S against hidden symbol `davs2_pb_1' can not be used when making a PIE object
/usr/bin/ld: libdavs2.a(dct8.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: libdavs2.a(mc-a2.o): relocation R_X86_64_32S against hidden symbol `davs2_pw_00ff' can not be used when making a PIE object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:195: recipe for target 'davs2' failed
make: *** [davs2] Error 1
```

#### Pre-requisites
 - **OS:** Ubuntu `18.04.3` *(Bionic Beaver)*
 - **Compiler:** GCC `7.4.0`
 - **`yasm` version:** `1.3.0`

[instructions]: https://github.com/pkuvcl/davs2/blob/master/README.md

**Comment by luofalei** [comment]
Please try `configure` using the following command. It may help.
```
./configure --enable-pic
```

**Comment by zhizhi-7699** [comment]
> Please try `configure` using the following command. It may help.
> 
> ```
> ./configure --enable-pic
> ```

请教如何在MIngW64或者msys2中成功编译呢~感谢，盼复

**Comment by tripulse** [comment]
@luofalei It worked without any issues, can you include that in the README.md?
