### ISSUE TITLE
build ffmpeg

### ISSUE THREAD

**Issue by ua0lnj** [pkuvcl/davs2#3]
In ffmpegavs2 no issues, therefore I write here.
Different variables in davs and ffmpeg:

davs2_param_t     ->  "i_info_level" in ffmpeg, "info_level" in davs.
davs2_seq_info_t  ->  "horizontal_size" in ffmpeg, "width" in davs.
davs2_seq_info_t  ->  "vertical_size" in ffmpeg, "height" in davs.
davs2_seq_info_t  ->  "output_bitdepth" in ffmpeg, "output_bit_depth" in davs.

**Comment by luofalei** [comment]
Thanks for the bug report. The `FFmpegAVS2` repository would be updated later by @hwrenx .

**Comment by hwrenx** [comment]
@ua0lnj Fixed.
