### ISSUE TITLE
duplicate symbol _bs_init in libdavs2.a(bitstream.o)

### ISSUE THREAD

**Issue by xanadu6291** [pkuvcl/davs2#8]
**Describe the bug**

When trying to build ffmpeg with --enable-libdavs2 and --enable-libbluray, it fails with error of the following:

LD	ffmpeg_g
duplicate symbol _bs_init in:
    /Volumes/ffmpeg_compile/lib/libdavs2.a(bitstream.o)
    /Volumes/ffmpeg_compile/lib/libbluray.a(libbluray_la-bits.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ffmpeg_g] Error 1

**To Reproduce**

1.Build both libdavs2 and libbluray library as static
2.Try to build ffmpeg with --enable-libdavs2 and --enable-libbluray options.
3.ffmpeg make process fails with duplicate symbol error as above.

**Expected behavior**

Can build ffmpeg without error.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.1 Mojave
 - Compiler: Apple LLVM version 10.0.0 (clang-1000.11.45.5)
 - yasm: nasm 2.14

**Additional context**

I have similar experience while building ffmpeg.  The cause is functions in one library is not defined as static.  So this time might be same reason.  Function bs_init in davs2/source/common/bitstream.cc is suspicious.

**Comment by luofalei** [comment]
Thanks pointing out this bug and it's very clear.
We added a prefix to global functions declared in this library in the latest commits, but I'm not able to test on this environment now.
Hope this could solve the problem, thanks.

**Comment by xanadu6291** [comment]
Thanks for prompt action.  I have confirmed that the problem was gone.
